read a;
read b;
print 1 * 2 * 3 * 4 * a * b + (1 + 2 + 3 + 4 + a * 1) + b * 1 + (a * 0 + b * 0);
print -a;
print -b;
print a - a;
print b - b;
print 0 * a();
print a() * 0;
print a - b;
print b - a;
print b() - b();
